### ISSUE TITLE
[Workload] State test: K8s Database Persistence test

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#1030] opened 2021-10-19 20:17 UTC
**Is your feature request related to a problem? Please describe.**
Proper persistence of databases in k8s should be checked

**Describe the solution you'd like**
K8s Database persistence test: if a mysql (or any popular database) image is installed:
1. if a statefulset with a elastic persistent volume is used: 5 points
2. if used directly with elastic persistent volumes: 3 points
3. if statefulset with a local persistent volume is used: 0 points
4. if used local volumes: -1 (caught by existing volume tests)

**Comment by lixuna** [comment] 2021-11-30 16:56
Duplicate of https://github.com/cncf/cnf-testsuite/issues/1025#issuecomment-947042586

**Comment by wavell** [comment] 2021-12-28 20:59
database_persistence
database_elastic_volumes
mysql_persistance
mysql_elastic_volumes
database_storage_class
mysql_storage_class

**Comment by agentpoyo** [comment] 2022-01-13 19:21
###  Acceptance Criteria 
---
###  Common steps
- [ ] Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `elastic_volumes`, I should see elastic_volumes test run with PASS results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-mysql/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite database_persistence`
- [ ] I can see results for database persistence.

### When I run `elastic_volumes`, I should see elastic_volumes test run with FAIL results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite database_persistence`
- [ ] I can see FAIL results for database persistence.

### When I run `workload`, I should see elastic_volumes test run during workloads:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-mysql/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite workload`
- [ ] I can see database persistence with points assigned during workload tests.

**Comment by agentpoyo** [comment] 2022-01-14 20:48
![1030_db_persistence_pass](https://user-images.githubusercontent.com/14348948/149583090-1aa45eee-0554-41c3-819a-08699784a208.png)

**Comment by agentpoyo** [comment] 2022-01-14 20:52
![1030_db_persistence_fail](https://user-images.githubusercontent.com/14348948/149583527-45ff3622-9ec6-4e2e-a5e5-34f9be29905c.png)

**Comment by agentpoyo** [comment] 2022-01-14 21:30
Passes but missing in the workload under STATE tests.  Opened https://github.com/cncf/cnf-testsuite/issues/1166

**Comment by agentpoyo** [comment] 2022-01-15 23:58
![1030_db_persistence_workload](https://user-images.githubusercontent.com/14348948/149641901-375d8e4c-4e1c-4c05-9b97-fd8b0727b3b8.png)

**Closed** 2022-01-24 22:11 UTC
Labels: state, 8 pts, workload, sprint22.01, v0.24.0
