### ISSUE TITLE
[BUG] Missing hash key Digest Error when running routed_logs and tracing test

### ISSUE THREAD

**Issue by iElephant** [cncf/cnf-testsuite#1610] opened 2022-08-24 17:59 UTC
**Describe the bug**

The following error is seen when running the workload test and the whole test suite exited: 

```shell
I, [2022-08-24 15:54:41 +02:00 #1666752]  INFO -- cnf-testsuite: KubectlClient.exec command: kubectl exec -n cnf-testsuite -ti  -- skopeo inspect docker://fluent/fluent-bit:1.9.7
I, [2022-08-24 15:54:41 +02:00 #1666752]  INFO -- cnf-testsuite: KubectlClient.exec stderr: error: pod, type/name or --filename must be specified

E, [2022-08-24 15:54:41 +02:00 #1666752] ERROR -- cnf-testsuite: Missing hash key: "Digest"
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /usr/share/crystal/src/hash.cr:1034:9 in '[]'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/cluster_utils.cr:90:63 in 'local_match_by_image_name'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/cluster_utils.cr:69:3 in 'local_match_by_image_name'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/fluentbit.cr:24:5 in '->'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /usr/share/crystal/src/primitives.cr:266:3 in 'all_cnfs_task_runner'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /workspace/src/tasks/utils/task.cr:19:9 in 'task_runner'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /workspace/src/tasks/workload/observability.cr:183:19 in '->'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: /usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
E, [2022-08-24 15:54:42 +02:00 #1666752] ERROR -- cnf-testsuite: src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
I, [2022-08-24 15:54:42 +02:00 #1666752]  INFO -- cnf-testsuite: exception with skipped exit code
```

It looks like the cluster_tools pod are not present in the cnf-testsuite namespace while the test is trying to run some command in the cluster tools pods, I went through the codes and it looks like the cluster tools pods are deleted in `host_network` test case, see security.cr:

```
desc "Check if potential attackers may gain access to a POD and inherit access to the entire host network. For example, in AWS case, they will have access to the entire VPC."
task "host_network", ["uninstall_cluster_tools", "kubescape_scan"] do |_, args|
```
And it never gets reinstalled, so it failed when routed_logs and tracing test cases are ran.

**To Reproduce**

1. Run individual host_network test case: `./cnf-testsuite host_network`
2. Then run the routed_logs or tracing test case: `./cnf-testsuite routed_logs`

**Expected behavior**
cluster tools presence should be checked before running related test cases.

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]: Linux
- Distro [e.g. Ubuntu]: Ubuntu
- Version [e.g. 18.04]: 18.04
- Architecture [e.g. x86, arm]: x87
- Browser [e.g. chrome, safari]: N/A

**Comment by HashNuke** [comment] 2022-09-05 23:51
@iElephant Thank you for reporting this issue with details to reproduce.
I've fixed this issue in a PR. Should be resolved in the main branch once the PR is reviewed and merged.

**Comment by iElephant** [comment] 2022-09-06 12:36
@HashNuke Thanks for the quick fix. Would you also consider adding the same dependency on the tracing test case? It wouldn't be a problem to run the cert/workload test but if we run the individual tracing test without the cluster_tools installed, it would also fail.

**Comment by agentpoyo** [comment] 2022-09-06 13:24
#### Acceptance Criteria

- [ ] When cluster tools is not installed and `routed_logs` is run, cnf-testsuite should install the cluster tools in order for this test to run.
- [ ] I should see cluster tools install and the `routed_logs` test complete without failure due to cluster tools not being installed.
- [ ] I can see a screenshot of the results here.

**Comment by agentpoyo** [comment] 2022-09-07 11:38
@HashNuke ,

The install of cluster_tools if missing was not successful. See screenshot below:

![1610_results](https://user-images.githubusercontent.com/14348948/188869259-c9ddbc9b-8c13-4abf-9149-bda4930f4777.png)

**Comment by agentpoyo** [comment] 2022-09-07 11:43
I found the issue @HashNuke , in order for me to successfully remove cluster_tools on my kind node, I had to just delete the cnf-testsuite namespace. So it appears if the namespace gets wiped, we'll see errors. I'll open a bug that should require the namespace to get recreated if missing or not found for cnf-testsuite tools to get installed to.

**Comment by agentpoyo** [comment] 2022-09-07 11:44
![1610_namespace_wiped](https://user-images.githubusercontent.com/14348948/188870546-1b6af436-dd5b-4950-b392-2c302020f008.png)

**Comment by agentpoyo** [comment] 2022-09-07 11:45
Marking this as reviewer approved but opening new found issue as a bug.

**Comment by agentpoyo** [comment] 2022-09-07 13:21
Opened related new bug found: https://github.com/cncf/cnf-testsuite/issues/1624

**Comment by HashNuke** [comment] 2022-09-07 15:16
@agentpoyo You are right. The namespace isn't created - so we have to ensure that too. Thanks for creating the other ticket.

**Closed** 2022-09-19 20:54 UTC
Labels: bug, 2 pts, Sprint 22.18, v0.33.0
