### ISSUE TITLE
[BUG] Task: Database Persistence -- Mysql is always found

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1213] opened 2022-02-11 21:29 UTC
**Describe the bug**
When running the task "database_persistence", mysql is always found even when not present in the cluster

**To Reproduce**

1. Run "database_persistence"

**Expected behavior**
Test case would be ignored, when mysql is not found

**Comment by agentpoyo** [comment] 2022-02-14 18:36
Hello @EricLo-417 ,

I installed our sample coredns CNF and could not reproduce this issue.  See screenshot below:

![1213_db_persistence_verify](https://user-images.githubusercontent.com/14348948/153925096-0b6d9274-95d8-4abd-9997-d25d7180efda.png)

Did you install a CNF that had a MySQL by chance but it was not entirely removed or deleted before running the test again? Can you share the log output when running the test along with perhaps `kubectl get pods --all-namespaces` to ensure mysql was not under the default output as the test will check all name-spaces on a cluster.

Thanks,

-Drew

**Comment by EricLo-417** [comment] 2022-02-14 20:54
Hey drew,

Sure running  `kubectl get pods -n default | grep my` produces nothing and then to double check I ran it without the grep and nothing seemed to be installed.

![image](https://user-images.githubusercontent.com/99511419/153944086-fc4d59ba-b8b3-48eb-a7df-5d0093180965.png)

Also based on your output, maybe i am confused but shouldn't it be skipped not "FAILED" as you also do not have mysql?

This mostly just comes from line 261 in state.cr

`if match` this seems to always resolve even though the field ":found" is false

I am fairly new to crystal (mostly come from javascript) so I could be misunderstanding the result

**Comment by agentpoyo** [comment] 2022-02-14 21:20
@EricLo-417 ,

You're right, I'm losing my mind. This should be skipping for me and not failing. We just suggested a code change in your PR, feel free to commit the suggested change and we can get this merged.

**Comment by agentpoyo** [comment] 2022-02-14 21:26
We tested your original change as well and went ahead and merged the PR https://github.com/cncf/cnf-testsuite/pull/1214

**Comment by agentpoyo** [comment] 2022-02-14 21:26
![1214](https://user-images.githubusercontent.com/14348948/153949103-a644912a-574a-4603-bcd7-2e080bb36123.png)

**Comment by agentpoyo** [comment] 2022-02-14 21:30
### Acceptance Criteria

- [ ] When I run `database_persistence`, I should see the test SKIPPED when there is no MySQL found or installed on the cluster.
- [ ] I can see a screenshot of the output above that the test SKIPS.

**Comment by agentpoyo** [comment] 2022-02-14 23:06
This fixed the issue you were seeing but exposed a new bug we are now working on when it was running the github actions and spec tests.

**Comment by agentpoyo** [comment] 2022-02-15 21:33
### Acceptance Criteria

- [x] When I run `database_persistence`, I should see the test SKIPPED when there is no MySQL found or installed on the cluster.
- [x] When I run `database_persistence`, I should see the test FAILED when there is MySQL but doesn't use elastic_volumes.
- [ ] When I run `database_persistence`, I should see the test PASSED when there is MySQL using elastic_volumes.
- [ ] I can see screenshots of he results.

**Comment by agentpoyo** [comment] 2022-02-15 21:34
![1213_db_persistence_SKIPPED](https://user-images.githubusercontent.com/14348948/154153048-3526ca32-cdf3-4d22-a73d-a2379c4876cd.png)

![1213_db_persistence_FAILED](https://user-images.githubusercontent.com/14348948/154153063-e7f04a82-42e6-4c59-9099-170b22ed6cf6.png)

**Closed** 2022-02-22 17:45 UTC
Labels: bug, state, 2 pts, workload, sprint22.04, v0.26.0
