### ISSUE TITLE
[Workload] Observability test: Check whether the cnf is outputting logs to stdout/stderr

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1072] opened 2021-10-28 23:47 UTC
## Title: [Workload] observability test: observable_logs

**Is your workload test idea related to a problem? Please describe.**
- It's considered a best-practice for containers / pods to output logs to stout/sterr so that commands like ```docker logs``` & ```kubectl get logs``` will return usful debug info.

**Describe the solution you'd like**
- Create a test that checks if a CNF is outputting logs to stdout/stderr.

**Test Category Name**
- Observability

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by denverwilliams** [comment] 2021-10-29 19:38
+1 for observability category tests.

**Comment by agentpoyo** [comment] 2021-10-29 19:39
+1 for observability category test for me

**Comment by wavell** [comment] 2021-10-29 19:39
https://12factor.net/logs
**Treat logs as event streams**
" Instead, each running process writes its event stream, unbuffered, to **stdout**. During local development, the developer will view this stream in the foreground of their terminal to observe the app’s behavior."

**Comment by wavell** [comment] 2021-10-29 19:39
+1 observabilituy

**Comment by agentpoyo** [comment] 2021-11-10 19:31
###  Acceptance Criteria 
---
### Documentation is updated:
- [ ] USAGE.md documentation updated
   - [ ] how to run
   - [ ] Description, remediation and details 
       - [ ] what the best practice is
       - [ ] why are we testing this
- [ ] CATEGORIES updated

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `log_output` I should see test FAILED results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_no_logs/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite log_output`
- [ ] I can see FAILED result output.

### When I run `log_output` I should see test PASSED results:
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml`
- [ ] Run `./cnf-testsuite log_output`
- [ ] I can see PASSED result output.

### Screenshots of output:
- [ ] I can see a screenshots of PASS/FAIL outputs

**Comment by agentpoyo** [comment] 2021-11-16 17:54
When I expect to see only FAILED, I also got a PASSED output:
![log_output_1](https://user-images.githubusercontent.com/14348948/142039354-5725929f-1df1-4fda-981d-31075f14047b.png)

**Comment by agentpoyo** [comment] 2021-11-16 17:55
![log_output_2](https://user-images.githubusercontent.com/14348948/142039406-35a9d0e9-81a5-4896-a6e0-3799ec5d8058.png)

**Comment by agentpoyo** [comment] 2021-11-16 17:56
@HashNuke 

Putting this back in Ready for Dev to verify if that's the expected output for your FAILED CNF example.

**Comment by agentpoyo** [comment] 2021-11-16 17:58
Oddly, I went back to run with LOG_LEVEL=info and I could not reproduce the previous PASS and FAIL output:

![log_output_3](https://user-images.githubusercontent.com/14348948/142039811-00929a5a-96c4-4dda-a373-79eb799643e2.png)

**Comment by agentpoyo** [comment] 2021-11-16 17:59
Approving for now, but we should perhaps look further into this if we see a PASS and FAIL output on CNF's to try and catch what could be causing such result.

**Comment by lixuna** [comment] 2021-11-17 16:44
@agentpoyo please check out this bug issue for "PASS and FAIL" https://github.com/cncf/cnf-testsuite/issues/1013

**Comment by agentpoyo** [comment] 2021-11-17 16:55
> @agentpoyo please check out this bug issue for "PASS and FAIL" #1013

Yeah,  I got that on my todo. I need to setup Microk8s but I think #1013 is something that should have been fixed now. But I'll see if I can't replicate it.

**Closed** 2021-11-17 17:02 UTC
Labels: observability, 8 pts, workload, v0.20.0, sprint46
