### ISSUE TITLE
[BUG] Error during `cert` where the logs indicate `ERROR - cnf-testsuite: no resource names found` - Helm Directory Bug

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1636] opened 2022-09-12 21:20 UTC
**Describe the bug**
We ran into another ERROR, and looking back at logs from runs using the previous binary this error was there but we were so focused on the SSL error we did not notice because the test continued to run past this error. This is what we see.

State Tests

```
E, [2022-09-07 16:39:17 -07:00 #2636266] ERROR -- cnf-testsuite: no resource names found
```

We get an identical error when the Security Tests start and then it finally errors out and no more test are run.

Any thoughts on what could be wrong?

**Comment by denverwilliams** [comment] 2022-09-12 21:41
Steps to reproduce on vulk03. 

```
./cnf-testsuite -l info cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml
./cnf-testsuite -l info single_process_type
```

```
pair@cnfdev03:~/workspace/denver/cnf-testsuite$ ./cnf-testsuite -l info single_process_type
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_runner args: #<Sam::Args:0x7f01a074d6a0 @arr=[], @named_args={}>
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: check_cnf_config args: #<Sam::Args:0x7f01a074d6a0 @arr=[], @named_args={}>
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: check_cnf_config cnf:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_config_list
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: find: find cnfs/* -name "cnf-testsuite.yml"
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: find response: ["cnfs/coredns/cnf-testsuite.yml"]
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: CNF configs found: 1
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: airgapped: false
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: generate_tar_mode: false
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: ensure_cnf_testsuite_yml_path
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: generate_and_set_release_name
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: generate_and_set_release_name config_yml_path: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: airgapped mode: false
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: generate_tar_mode: false
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: ensure_cnf_testsuite_yml_path
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: ensure_cnf_testsuite_yml_dir
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: parsed_config_file: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: parsed_config_file: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_installation_method
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_installation_method config: #<Totem::Config:0x7f01a079ebe0>
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_installation_method config: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory_parameter_split :
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory_parameter_split :
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory :  parameters:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: release_name: coredns
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: helm_directory:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: manifest_directory:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: Building helm_directory and manifest_directory full paths
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: full_helm_directory: /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/ exists? true
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: full_manifest_directory: /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/ exists? true
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_destination_dir config_file: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: parsed_config_file: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: release_name: coredns
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf destination dir: /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: ensure_cnf_testsuite_yml_dir
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: USING EXPORTED CHART PATH
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: install_parameters
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory_parameter_split : stable/coredns
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory : stable/coredns parameters:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory_parameters :
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: namespace_from_parameters:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: namespace_from_parameters namespace:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_workload_resources
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_installation_method config : CNFManager::Config
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: config_cnf_config: {destination_cnf_dir: "/home/pair/workspace/denver/cnf-testsuite/cnfs/coredns", source_cnf_file: "cnfs/coredns/cnf-testsuite.yml", source_cnf_dir: "cnfs/coredns/", yml_file_path: "cnfs/coredns/", install_method: {HelmChart, "stable/coredns"}, manifest_directory: "", helm_directory: "", source_helm_directory: "", helm_chart_path: "/home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/exported_chart", manifest_file_path: "/home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/temp_template.yml", release_name: "coredns", service_name: "coredns-coredns", helm_repository: {name: "stable", repo_url: "https://cncf.gitlab.io/stable"}, helm_chart: "stable/coredns", helm_values: "", helm_install_namespace: "cnfspace", rolling_update_tag: "", container_names: [{"name" => "", "rolling_update_test_tag" => "", "rolling_downgrade_test_tag" => "", "rolling_version_change_test_tag" => "", "rollback_from_tag" => ""}], white_list_container_names: ["falco", "node-cache", "nginx", "coredns", "calico-node", "kube-proxy", "nginx-proxy"]}
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: parsed_config_file: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_installation_method
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_installation_method config: #<Totem::Config:0x7f01a079ec80>
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cnf_installation_method config: cnfs/coredns/cnf-testsuite.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory_parameter_split :
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory_parameter_split :
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: directory :  parameters:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: release_name: coredns
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: helm_directory:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: manifest_directory:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: Building helm_directory and manifest_directory full paths
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: full_helm_directory: /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/ exists? true
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: full_manifest_directory: /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/ exists? true
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: EXPORTED CHART PATH: /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/exported_chart
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: Helm::generate_manifest_from_templates command: helm template coredns /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/exported_chart > /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/temp_template.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: before generate command: ls -alR /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/exported_chart
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: before generate command: ls -alR cnfs
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: helm command: helm template -n cnfspace coredns  /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/exported_chart > /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/temp_template.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: Helm.template output:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: Helm.template stderr:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: after generate command: ls -alR /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/exported_chart
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: after generate command: ls -alR cnfs
✖️  🏆 FAILED: More than one process type used 🦖 ⚖️👀
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: parse_manifest_as_ymls template_file_name: /home/pair/workspace/denver/cnf-testsuite/cnfs/coredns/temp_template.yml
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: workload_resource_by_kind kind: Deployment
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: workload_resource_by_kind kind: Service
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: workload_resource_by_kind kind: Pod
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: workload_resource_by_kind kind: ReplicaSet
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: workload_resource_by_kind kind: StatefulSet
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: workload_resource_by_kind kind: DaemonSet
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: resource names: []
E, [2022-09-12 16:52:39 -04:00 #1870623] ERROR -- cnf-testsuite: no resource names found
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: cmd: /home/pair/workspace/denver/cnf-testsuite/cnf-testsuite single_process_type
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_type_by_task
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: points: {"name" => "single_process_type", "tags" => "microservice, dynamic, workload, essential, cert", "pass" => 100}
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: resp: ["microservice", "dynamic", "workload", "essential", "cert"]
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_type x: microservice acc:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_type x: dynamic acc:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_type x: workload acc:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_type x: essential acc:
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_type x: cert acc: essential
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: task_type: essential
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: upsert_task: task: single_process_type has status: failed and is awarded: 0 points
I, [2022-09-12 16:52:39 -04:00 #1870623]  INFO -- cnf-testsuite: results yaml: {"name" => "cnf testsuite", "status" => nil, "command" => "/home/pair/workspace/denver/cnf-testsuite/cnf-testsuite single_process_type", "points" => nil, "exit_code" => 0, "items" => [{"name" => "single_process_type", "status" => "failed", "type" => "essential", "points" => 0}]}
```

**Comment by denverwilliams** [comment] 2022-09-19 20:19
Quick fix for this issue: 

```
Hello Rich,

We're working on a fix for the long term as we believe the error seen is being caused due to the relative path where the chart/ directory and cnf-testsuite.yml file reside.

The quick workaround fix would be to make sure the cnf-testsuite.yml and the chart/ directory for the CNF are in the same directory.

You can see the layout in the following sample CNF we have available in the code at https://github.com/cncf/cnf-testsuite/tree/main/sample-cnfs/sample_coredns

If you have any questions or concerns, feel free to reach out.

Thanks,

-Drew

**Comment by denverwilliams** [comment] 2022-09-19 20:21
New ticket for fixing the issue long-term is here: cncf/cnf-testsuite#1645

**Comment by agentpoyo** [comment] 2022-09-22 12:58
AC and tests will be done in https://github.com/cncf/cnf-testsuite/issues/1645

**Closed** 2022-10-06 21:03 UTC
Labels: bug, 5 pts, v0.34.0, sprint22.20
