### ISSUE TITLE
[BUG] `install_opa` installs to the `default` namespace, it should install to it's own namespace and not default

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1578] opened 2022-07-25 19:32 UTC
**Describe the bug**
`install_opa` installs gatekeeper to the `default` namespace when it should install to the `cnf-testsuite` or another namespace that is not `default`.

**To Reproduce**
Run `./cnf-testsuite install_opa` and you should see gatekeeper running under the `default` namespace when viewing `kubectl get pods --all-namespaces`

**Expected behavior**
OPA (gatekeeper) should install to the `cnf-testsuite` or another namespace that is not `default`.

**Screenshots**
![install_opa_default_namespace](https://user-images.githubusercontent.com/14348948/180859524-ffabcb4c-0709-4656-b719-066f501e22cb.jpg)

**Comment by HashNuke** [comment] 2022-08-03 14:49
This is a duplicate of #1593. Moving this to peer review since this has been completed with a PR to #1593.

**Comment by agentpoyo** [comment] 2022-08-08 19:38
#### Acceptance Criteria

- [ ] When I `install_opa`, I should see that it installs to a namespace that is not the `default` namespace
- [ ] I can see the output of `kubectl get pods -all-namespaces` here and see OPA gatekeeper is not in the default namespace.

**Comment by agentpoyo** [comment] 2022-08-08 19:39
![1578_install_opa](https://user-images.githubusercontent.com/14348948/183500493-2a8414ba-82d2-4141-b179-c28f59e1d8c1.png)

**Closed** 2022-08-16 16:18 UTC
Labels: bug, 3 pts, sprint22.16, v0.32.1
