### ISSUE TITLE
[BUG] Some of the tests produce PASSED and FAILURE results

### ISSUE THREAD

**Issue by robert-hillier** [cncf/cnf-testsuite#1013] opened 2021-10-07 15:20 UTC
**Describe the bug**
When running the tests, some report PASSED and FAILED, and I'm not sure which one is correct

**To Reproduce**
Run the `cnf-testsuite workload` command

**Expected behavior**
Tests should either pass or fail

**Environment:**
-  Ubuntu 20.04 (x86_64)
-  Microk8s 1.21

**Screenshots**
```
✔️  PASSED: Replicas increased to 3 📦📈
✖️  FAILURE: Replicas did not reach 3 📦📈

Replica failure can be due to insufficent permissions, image pull errors and other issues.
Learn more on remediation by viewing our USAGE.md doc at https://bit.ly/capacity_remedy

✔️  PASSED: Replicas decreased to 1 📦📉
✖️  FAILURE: Replicas did not reach 1 📦📉

Replica failure can be due to insufficent permissions, image pull errors and other issues.
Learn more on remediation by viewing our USAGE.md doc at https://bit.ly/capacity_remedy

Scalability final score: -10 of 20
```
```
pod-network-latency chaos test failed 🗡️💀♻️
pod-network-latency chaos test failed 🗡️💀♻️
pod-network-latency chaos test failed 🗡️💀♻️
✖️  FAILED: pod_network_latency chaos test failed 🗡️💀♻️
✔️  PASSED: pod_network_latency chaos test passed 🗡️💀♻️
pod-network-corruption chaos test failed 🗡️💀♻️
pod-network-corruption chaos test failed 🗡️💀♻️
pod-network-corruption chaos test failed 🗡️💀♻️
✖️  FAILED: pod_network_corruption chaos test failed 🗡️💀♻️
✔️  PASSED: pod_network_corruption chaos test passed 🗡️💀♻️
pod-network-duplication chaos test failed 🗡️💀♻️
pod-network-duplication chaos test failed 🗡️💀♻️
pod-network-duplication chaos test failed 🗡️💀♻️
✖️  FAILED: pod_network_duplication chaos test failed 🗡️💀♻️
✔️  PASSED: pod_network_duplication chaos test passed 🗡️💀♻️
```

**Comment by agentpoyo** [comment] 2021-12-08 16:03
@robert-hillier 

I believe these duplicates were fixed but I'm doing a test now on MicroK8s v1.21 now to see if I can't reproduce this issue.

**Comment by agentpoyo** [comment] 2021-12-08 16:15
Doesn't seem to FAIL and then PASS but I am seeing the plain text output of a FAILURE before the actual intended output that was addressed previously but somehow is displaying again. I will open a bug on this.

![bug_1013_resilience_output_mk8s](https://user-images.githubusercontent.com/14348948/145242981-e3714270-9f6a-489b-ba38-4fa0e32dacea.jpg)

@robert-hillier,

If you can, try updating to the latest cnf-testsuite version and let us know if you are still seeing both FAIL and PASS on the resilience tests for the CNF you are testing against. If you do see the same results, if you can run in INFO or DEBUG, that would be great:  `LOG_LEVEL=info ./cnf-testsuite workload` or you can just run the resilience where the failures happend by specifying them with `LOG_LEVEL=info ./cnf-testsuite resilience`

Thanks,

-Drew

**Comment by agentpoyo** [comment] 2022-01-04 02:47
Cannot reproduce this issue, closing. Opened bug https://github.com/cncf/cnf-testsuite/issues/1131 on other findings.

**Closed by agentpoyo** 2022-01-04 02:47 UTC
Labels: bug, sprint45, sprint46, sprint47
