### ISSUE TITLE
[BUG] Node Drain issues

### ISSUE THREAD

**Issue by EricLo-417** [cncf/cnf-testsuite#1727] opened 2023-01-24 21:51 UTC
**Describe the bug**
Not really a bug so much as a better understanding of why node drain is failing without any noticeable errors.
Could be a problem with trying to run cnf-testsuite in a kind env

***Logs***

***Node Drain Pod***
`time="2023-01-24T21:31:53Z" level=info msg="[Confirmation]: node-drain chaos has been injected successfully"
time="2023-01-24T21:31:53Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2023-01-24T21:31:53Z" level=info msg="[Status]: Checking whether application containers are in ready state"
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are as follows" container=chf Pod=chf-cnf-586f874bfb-trm9p Readiness=true
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are as follows" Pod=chf-cnf-586f874bfb-trm9p Readiness=true container=chf-leader-elect
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are as follows" Readiness=true container=chf Pod=chf-cnf-586f874bfb-wqllj
time="2023-01-24T21:31:53Z" level=info msg="[Status]: The Container status are
 as follows" Readiness=true container=chf-leader-elect Pod=chf-cnf-586f874bfb-wqllj
time="2023-01-24T21:31:55Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2023-01-24T21:31:55Z" level=info msg="[Status]: The status of Pods are as follows" Status=Running Pod=chf-cnf-586f874bfb-trm9p
time="2023-01-24T21:31:55Z" level=info msg="[Status]: The status of Pods are as follows" Pod=chf-cnf-586f874bfb-wqllj Status=Running
time="2023-01-24T21:31:57Z" level=info msg="[Status]: Getting the status of target nodes"
time="2023-01-24T21:31:57Z" level=info msg="The Node status are as follows" Ready=true Node=ktx-ancient-architect-worker2
time="2023-01-24T21:31:57Z" level=info msg="[The End]: Updating the chaos result of node-drain experiment (EOT)"`

***CNF-Testsuite Output***
2023-01-24 16:32:11.965  INFO --- c.m.k.Context                            :  EVENT: SUCCESS 2023-01-24T16:26:42.767-0500 (5m) Competed CNF Test Suite node_drain Command for testCHF
✖️  🏆 FAILED: node_drain chaos test failed 🗡️💀♻️

***Kind Config***
[kind-config.zip](https://github.com/cncf/cnf-testsuite/files/10494273/kind-config.zip)

***Images***
![Nodes from Lens](https://user-images.githubusercontent.com/99511419/214428240-f9f112af-ae1b-40a4-8bed-05e7d73affca.png)
![Pods from Lens](https://user-images.githubusercontent.com/99511419/214428246-181e59e2-060e-49c4-a295-c0993a29df6e.png)

**Comment by lixuna** [comment] 2023-03-21 14:29
@HashNuke were you able to recreate this issue?

**Comment by HashNuke** [comment] 2023-06-27 12:54
Attempted to reproduce this issue with a sample CNF. The `node_drain` test output seems fine.
I used a variation of the kind config attached on the ticket description (I've posted that below).

Please let us know if there is any other config/info we can use to reproduce this issue.

## Screenshot of `node_drain` test output

<img width="1327" alt="CleanShot 2023-06-27 at 19 48 48@2x" src="https://github.com/cncf/cnf-testsuite/assets/84005/9527334c-3cf1-4d04-bfd4-23da416db32e">

## Commands used to run the test

```shell
export KIND_CLUSTER_NAME="test-1727"
export KUBECONFIG="${PWD}/${KIND_CLUSTER_NAME}.kubeconfig"
kind create cluster --name $KIND_CLUSTER_NAME \
--kubeconfig $KUBECONFIG \
--config kind-config.yml

./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample-coredns-cnf
./cnf-testsuite node_drain
```

## kind config used

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-image-registry:5000"]
      endpoint = ["localhost:5000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: ""
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: ""
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: ""
```

**Comment by HashNuke** [comment] 2023-06-27 14:22
Can you try running the test using the below command and share the log output?

```shell
LOG_LEVEL=debug ./cnf-testsuite node_drain > test-output.log
```

**Comment by HashNuke** [comment] 2023-07-17 04:41
Looked into the logs that the Matrixx team had shared over (cncf slack). But in this case the node_drain test wasn't being run. Will wait for the debug output logs to be shared with the node_drain test being run with sufficient schedulable nodes.

**Comment by HashNuke** [comment] 2023-10-24 13:01
My earlier attempts to reproduce this ticket was only using one CNF. There were two issues identified with `node_drain` recently. Both required reproducing with multiple CNFs installed.

* [FIXED] #1834
  * Node wasn't being uncordoned after running the test for a CNF. So the next CNF to test would have one node less to work with.
  *  The fix was released in a recent version of the testsuite. So the latest release of the testsuite [0.44.4](https://github.com/cncf/cnf-testsuite/releases/tag/v0.44.4) includes this fix.
* #1838 - This issue existed along with 1834. But was only revealed after 1834 was fixed.
  * The testsuite was timing out waiting for Litmus Chaos verdict. And was proceeding to mark the CNF as failed.
  * And since the previous experiment is still running, it would interfere with the next CNF being tested.
  * [PR-1839](https://github.com/cncf/cnf-testsuite/pull/1839) is open for this issue and should fix it. Will post an update here once this is merged.

**Comment by EricLo-417** [comment] 2023-10-24 13:42
@agentpoyo  
We just updated to 0.44.4 so we should see results sometime today or tomorrow, ill let you know when we get a test to complete

**Comment by lixuna** [comment] 2023-12-12 15:38
@daniel-wilmes @EricLo-417 Is this issue still occurring? If so, please share additional information to help with debugging.

**Comment by daniel-wilmes** [comment] 2023-12-12 15:51
Sent log file through slack

**Comment by lixuna** [comment] 2023-12-19 15:29
@HashNuke @agentpoyo please see slack for logs

**Comment by HashNuke** [comment] 2023-12-20 23:05
@lixuna We just confirmed that `node_drain` is passing according to the logs shared.

**Comment by HashNuke** [comment] 2023-12-24 01:38
This issue has been fixed. Moving this to peer review.

**Comment by agentpoyo** [comment] 2024-01-02 16:26
#### Acceptance Criteria

- [ ] When I view the logs, I can see that node_drain is passing the tests.

**Closed** 2024-01-23 16:29 UTC
Labels: bug
