### ISSUE TITLE
[Maintenance] Update version of Crystal lang to GA Release, v1.0.0

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#771] opened 2021-05-11 17:05 UTC
**Describe the maintenance item**
- the CNF Test Suite currently supports Crystal Language version Crystal 0.35.1 "and the locked in shards versions"
- Crystal's GA 1.0 release has been available since March 22, 2021
- Update the CNF Test Suite to support Crystal's 1.0 release, see https://github.com/crystal-lang/crystal/releases/tag/1.0.0

**Expected behavior**
- the CNF Test Suite will function as expected after updating Crystal from 0.35.1 to 1.0

**How will this be tested? aka Acceptance Criteria (optional)**

- [ ] All documentation is updated to mention the updated Crystal version, 1.0.0
- [ ] Install works as expected
- [ ] Running all tests works as expected
- [ ] Running workload-only works as expected
- [ ] Running platform-only works as expected
- [ ] Running individual test categories works as expected
- [ ] Running individual tests works as expected
- [ ] tbd, add more expectations as needed

**Additional context**
- the current version of Crystal on CNF Test Suite (v0.35.1) is 3 versions behind the 1.0.0 release

**Comment by HashNuke** [comment] 2021-06-26 12:21
Made an attempt (branch: `crystal-v1`). Noticed that we are using two docker images in the github actions
* `conformance/crystal`
* `conformance/offline`

I could not find the source docker files for these images to attempt an upgrade.

### Below are my notes from the exercise

- Crystal 1.0.0
    - [Changelog](https://github.com/icyleaf/halite/blob/master/CHANGELOG.md)
    - No code changes
    - Only upgrade to 0.7.0
- icyleaf/halite
    - [Changelog](https://github.com/icyleaf/totem/blob/master/CHANGELOG.md)
    - No code changes
    - Only upgrade to 0.12.0
- mrrooijen/commander
    - [Changelog](https://github.com/mrrooijen/commander/blob/master/CHANGELOG.md)
    - No upgrade required
    - No code changes
- vulk/sam.cr
    - No changelog
    - Have to make this compatible with Crystal v1.0.0
    - Temporarily forked it as `HashNuke/sam.cr` and updated shard.yml to allow Crystal 1.0.0 ([working branch](https://github.com/HashNuke/sam.cr/tree/v1-upgrade))
- straight-shoota/crinja
    - [Changelog](https://github.com/straight-shoota/crinja/blob/master/CHANGELOG.md)
    - No code changes
- Sija/retriable.cr
    - No code changes required
    - [Sent PR](https://github.com/Sija/retriable.cr/pull/11) to the repo to allow Crystal v1.0.0. Temporarily building from `HashNuke/retriable.cr`
- crystal-ameba/ameba
    - No changelog available
    - Be brave and upgrade to 0.14.3. Let us see what breaks.

**Comment by HashNuke** [comment] 2021-06-30 17:57
**Update: 30 June 2021**

* GitHub Actions build now uses a custom image for crystal now for the github actions.
* Added this new dockerfile to the repo incase we want to update the Crystal version again sometime later.
* Temporarily pushed this docker image to my own namespace `hashnuke/crystal-custom:1.0.0-alpine-r1`.
* All tests except the 3 airgapped tests are passing according to the [latest build as of this comment](https://github.com/cncf/cnf-testsuite/actions/runs/987219699).
* Team confirmed that there might be an issue with the self-hosted github action runners.

Will try running the tests tomorrow after the self-hosted runners are fixed.

**Comment by HashNuke** [comment] 2021-07-01 14:38
**Update: 01 July 2021**
* [The build](https://github.com/cncf/cnf-testsuite/actions/runs/987219699) is green now after the team fixed the self-hosted runners.
* Next: Will check if icr can be added back.

**Comment by HashNuke** [comment] 2021-07-05 14:19
**Update: 05 July 2021**

[Build is green](https://github.com/cncf/cnf-testsuite/actions/runs/999807238). But I'm maintaining the following forks temporarily:
* [Fork of icr](https://github.com/HashNuke/icr/tree/crystal-v1) - `crystal-v1` branch
* [Fork of crystal-readline](https://github.com/HashNuke/crystal-readline/tree/crystal-v1) - `crystal-v1` branch. Required by icr
* [Fork of sam.cr](https://github.com/HashNuke/sam.cr/tree/v1-upgrade) - `v1-upgrade` branch

**Comment by HashNuke** [comment] 2021-07-11 14:00
We cannot merge this until icr shard supports Crystal 1.0, which in turn depends on crystal-readline. 
* We'll have to wait until this [PR is merged](https://github.com/crystal-lang/crystal-readline/pull/5)
* Added the blocked label to this task.

**Comment by williscool** [comment] 2021-07-21 06:08
@HashNuke looks like you should be able to merge this now

https://github.com/crystal-lang/crystal-readline/pull/5

**Comment by HashNuke** [comment] 2021-07-22 11:37
**Update**: Sent [PR-131](https://github.com/crystal-community/icr/pull/131) to icr to update Crystal version.

**Comment by agentpoyo** [comment] 2021-08-05 01:49
Acceptance Criteria:

- [ ] Setup and configure crystal v1.0.0 on workstation or instance that cnf-testsuite will be installed onto. See https://crystal-lang.org/install/ for more details for OS version used.
- [ ] Verify crystal version is 1.0.0 with `crystal version` command.
- [ ] Download source from git repo for cnf-testsuite: `git clone git@github.com:cncf/cnf-testsuite.git`
- [ ] `cd cnf-testsuite` and then run shards install to verify shards dependencies are downloaded without error: `shards install`
- [ ] Now run `crystal build src/cnf-testsuite.cr --warnings none` if shards install had no errors to build the cnf-testsuite binary.
- [ ] Once built, you can verify the binary by running `./cnf-testsuite version` and it should tell you the current main branch version, ex. `CNF TestSuite version: main-2021-08-04-230419-fba71fc`
- [ ] Now you can run `cnf_setup` and `workload` tests.
- [ ] After successful cnf_setup, I can see screenshots of a successful workload or other test performed on cnf-testsuite using crystal v1.0.0

**Comment by agentpoyo** [comment] 2021-08-05 20:46
![image](https://user-images.githubusercontent.com/14348948/128418784-07c83088-f5c6-4837-b1a3-5e98886792b7.png)

**Comment by agentpoyo** [comment] 2021-08-05 21:09
![image](https://user-images.githubusercontent.com/14348948/128421536-a49995cd-1ca1-44ba-8f26-5099702a83f8.png)

**Comment by lixuna** [comment] 2021-08-06 17:47
@agentpoyo @denverwilliams @wavell @HashNuke what is the level of effort in points for this issue? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment] 2021-08-06 20:05
8pts

**Closed** 2021-08-12 17:46 UTC
Labels: 8 pts, maintenance, sprint37, sprint38, sprint39, v0.14.0
