### ISSUE TITLE
[Feature] when increase_decrease_capacity test fails, provide suggestions on how to improve a CNF

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#632] opened 2021-03-03 17:03 UTC
### [Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/632#issuecomment-789903036) 

**Is your feature request related to a problem? Please describe.**
- an end user's CNF failed the `increase_decrease_capacity` test and requested that the CNF Test Suite provide suggestions on how to demonstrate a CNF's ability to increase/decrease capacity 

**User Story:**

**Given** that I am a CNF Developer running the CNF Test Suite, 
**When** my CNF fails the test called `increase_decrease_capacity`,
**Then** I would like to see suggestions on how to demonstrate the ability to increase/decrease capacity so that I can modify my CNF to follow cloud native best practices 

**Describe the solution you'd like**
What we see now: 
- a minimal note that the test failed
 ```
Increase capacity failure:✖️  FAILURE: Replicas did not reach 3📦📈
Decrease capacity failure: ✖️  FAILURE: Replicas did not reach 1📦📉
```

What we would like to see: 
- an expanded note that the test failed with references

**Describe alternatives you've considered**
- update the report log
- add to debug log
- update the test categories or usage documentation in this repo
- link to external github repo
- link to existing external documentation
- create new external documentation

**Selected MVP items for this feature**
- Add a remediation (collapsable) section on USAGE doc for the increase decrease capacity test
   - Paragraph on what to check for remediation when this test fails
   - Links to K8s docs specific to addressing the increase/decrease capacity test
   - Links to  other relevant docs for additional information
- Show message on console output for remediation (link or paragraph)
  - Add link to the new remediation documentation in USAGE.md in output
- Show message in results yaml file for remediation (link or paragraph)
  - Add link to the new remediation documentation in USAGE.md in results file

**Additional context**
- TBD

Review initial issue(s) adding this test 

- [#24] Scalability Test: Can CNF increase and decrease capacity? For supplemental information 
- [#71] Installable test: Can the CNF perform a rolling version upgrade? #71

**Comment by taylor** [comment] 2021-03-03 17:17
What is MVP for this issue - increase_decrease_capacity test failed, what are suggestions to pass this test?
- This feature would only give specific feedback for the one single test that failed
- Paragraph of what to check if you fail the increase + decrease capacity test
- Embed recommendation and links in code as MVP
- Show on console output
- Show in results yaml file
- Add documentation collapsable section on USAGE doc
- Add link to this document in console output and results yaml
- Paragraph on what to check if you fail
- Links to K8s and other docs for additional information
- URL to K8s docs specific to the increase/decrease capacity test


----

Discussed items that are out of scope
- More specific feedback for each CNF tested
- Sentence explaining what the increase + decrease capacity test is for. Why is it valuable?

**Comment by lixuna** [comment] 2021-03-03 17:19
### Acceptance Criteria DRAFT - based on #606

---
###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update documentation 
- [ ] https://github.com/cncf/cnf-conformance/blob/master/CNF_CONFORMANCE_YML_USAGE.md
- [ ] tbd

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A


### I would expect a CNF to FAIL if it cannot increase or decrease capacity:
- [ ] Follow common steps above
- [ ]  Run  `./cnf-conformance workload` (tbd) 
- [ ]  tbd: run one test `increase_decrease_capacity`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see FAILED for the test
- [ ]  I expect to see expanded details with the FAILED message (tbd)

### Screenshots of all command and workload command output
- [ ] I can see a screenshot testing the `workload` test with a CNF using images from the private Docker Hub repository

**Comment by taylor** [comment] 2021-03-03 17:21
Review initial issue(s) adding this test 

- [24] Scalability Test: Can CNF increase and decrease capacity? For supplemental information 
- [71] Installable test: Can the CNF perform a rolling version upgrade? #71

**Comment by lixuna** [comment] 2021-03-03 17:55
### Level of effort in points: 0,1,2,3,5,8,13,21: 

@denverwilliams -
@agentpoyo - 
@wavell - 
@williscool - 
@nupejosh - 
@taylor - 
@lixuna -

**Comment by agentpoyo** [comment] 2021-04-07 18:39
We need to determine a good way to test this as a test was not created to go through the Acceptance Criteria steps.

@williscool @lixuna @taylor @wavell @denverwilliams

**Comment by lixuna** [comment] 2021-04-08 14:44
@agentpoyo during planning, this issue was intended to modify an existing test called `increase_decrease_capacity`

In this issue, we talked about creating an example cnf that would fail, so that the failure message would say something like what is in https://github.com/cncf/cnf-conformance/pull/644/files.

Is the `sample_fail_increase_capacity` available to use in the A/C?

**Comment by agentpoyo** [comment] 2021-04-08 14:55
> @agentpoyo during planning, this issue was intended to modify an existing test called `increase_decrease_capacity`
> 
> In this issue, we talked about creating an example cnf that would fail, so that the failure message would say something like what is in https://github.com/cncf/cnf-conformance/pull/644/files.
> 
> Is _a sample CNF_ `sample_fail_increase_capacity` available to use in the A/C?

No

@lixuna

**Comment by lixuna** [comment] 2021-04-08 16:32
I moved the issue back to In Progress.

What's left: 
- create a sample cnf to test the new expected behavior

**Comment by agentpoyo** [comment] 2021-04-14 22:36
I actually had another peer review fail on the replicas:

![image](https://user-images.githubusercontent.com/14348948/114788814-bf245400-9d47-11eb-8302-07d597d60b57.png)

But cannot reproduce now. This was after I used a CNF that had a bogus/invalid `install_script` at the time.

**Comment by lixuna** [comment] 2021-04-19 20:59
@williscool please update "To addresss this issue" to "To address this issue"

**Comment by williscool** [comment] 2021-04-22 20:38
fixing spellin

https://github.com/cncf/cnf-testsuite/pull/732/

**Comment by agentpoyo** [comment] 2021-04-23 02:48
I think I found a CNF we can use that fails one of these tests to display output.

**Comment by agentpoyo** [comment] 2021-04-23 03:03
### Acceptance Criteria DRAFT - based on #606

---
###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update documentation 
- [ ] Go to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-the-increasing-and-decreasing-of-capacity
- [ ] I expect to see a remediation (collapsable) section the increase decrease capacity test
- [ ] When I expand the collapsed section
- [ ] I expect to see a paragraph on what to check for remediation when this test fails
- [ ] I expect to see links to K8s docs specific to addressing the increase/decrease capacity test
- [ ] If relevant, I expect to see links to other docs for additional information

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

## Show message on console output for remediation

### I would expect to see a remediation message in the console output when a CNF fails either increase or decrease capacity:
- [ ] Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-statefulset-cnf/cnf-conformance.yml`
- [ ]  Run ./cnf-conformance  `increase_decrease_capacity`
- [ ]  I expect to see the output from the test
- [ ] I would expect to see the FAILED increase capacity message. eg: "✖️  FAILURE: Replicas did not reach 3📦📈"
- [ ]  I expect to see a message about remediation with a link to the USAGE document.

## Show message in results yaml file for remediation 

### I would expect to see a remediation message in the results yaml file when a CNF fails the increase capacity test:
- [ ] Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running:  `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample-statefulset-cnf/cnf-conformance.yml`
- [ ]  Run ./cnf-conformance  `workload`
- [ ]  I expect to see the output from the test
- [ ] I would expect to see the FAILED increase capacity message in the results yaml file.
- [ ]  I expect to see a message about remediation with a link to the USAGE document in the results yaml file

### Screenshots of all command and workload command output
- [ ] I can see a screenshot of the remediation test output after it FAILS.

**Comment by agentpoyo** [comment] 2021-04-23 03:04
![image](https://user-images.githubusercontent.com/14348948/115812266-bb7f7580-a3b6-11eb-8cba-770c6503052d.png)

**Comment by agentpoyo** [comment] 2021-04-23 03:07
The remediation is not showing up in the results yaml file as expected and planned @williscool @wavell @denverwilliams 

![image](https://user-images.githubusercontent.com/14348948/115812482-144f0e00-a3b7-11eb-8831-f413ecf358c8.png)

**Comment by williscool** [comment] 2021-04-23 06:28
@wavell @denverwilliams @agentpoyo 

I had forgotten on the test case a few weeks ago.

`sample-fragile-state` is the one that doesn't startup properly. was trying to play around with using it to make this test fail but will hand it off to you guys now

**Comment by agentpoyo** [comment] 2021-04-23 13:07
> @wavell @denverwilliams @agentpoyo
> 
> I had forgotten on the test case a few weeks ago.
> 
> `sample-fragile-state` is the one that doesn't startup properly. was trying to play around with using it to make this test fail but will hand it off to you guys now

I'll take a stab at it today.

**Comment by agentpoyo** [comment] 2021-04-23 16:34
> > @wavell @denverwilliams @agentpoyo
> > I had forgotten on the test case a few weeks ago.
> > `sample-fragile-state` is the one that doesn't startup properly. was trying to play around with using it to make this test fail but will hand it off to you guys now
> 
> I'll take a stab at it today.

This fails the same way the CNF I found. So I think we are good.

**Comment by williscool** [comment] 2021-04-26 16:07
> > > @wavell @denverwilliams @agentpoyo
> > > I had forgotten on the test case a few weeks ago.
> > > `sample-fragile-state` is the one that doesn't startup properly. was trying to play around with using it to make this test fail but will hand it off to you guys now
> > 
> > 
> > I'll take a stab at it today.
> 
> This fails the same way the CNF I found. So I think we are good.

sweeeeet!!

**Closed** 2021-04-26 16:22 UTC
Labels: 5 pts, big planning, enhancement, sprint28, sprint29, sprint30, sprint31, sprint32, v0.10.5
